### ISSUE TITLE
 "yii: command not found" while try to run command "yii gearman/start --fork=true"

### ISSUE THREAD

**Issue by PurnimaG** [Filsh/yii2-gearman#4]

**Comment by filsh** [comment]
./yii gearman/start --fork=true

**Comment by PurnimaG** [comment]
But it still gives me 

/yii: command not found

I am running this command in project root .

**Comment by filsh** [comment]
dot(.) missing, run this command "./yii gearman/start --fork=true" from your project root

**Comment by PurnimaG** [comment]
Thanks a lot. Its working now.

**Comment by PurnimaG** [comment]
Hi , 

How can I empty the job queue after job done.
